name: opal-example

services:
  broadcast_channel:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  opal_server:
    image: permitio/opal-server:latest
    environment:
      OPAL_BROADCAST_URI: postgres://postgres:postgres@broadcast_channel:5432/postgres
      OPAL_POLICY_REPO_URL: https://github.com/permitio/opal-example-policy-repo
      OPAL_STATISTICS_ENABLED: "true"
      OPAL_LOG_LEVEL: INFO
      OPAL_SERVER_PORT: "7002"
      OPAL_LISTEN_ADDRESS: "0.0.0.0"

    ports:
      - "7002:7002"
    depends_on:
      - broadcast_channel

  opal_client:
    image: permitio/opal-client:latest
    environment:
      OPAL_SERVER_URL: http://opal_server:7002
      OPAL_STATISTICS_ENABLED: "true"
      OPAL_LOG_LEVEL: INFO
    depends_on:
      - opal_server
    ports:
      - "7000:7000"
    command: sh -c "exec ./wait-for.sh opal_server:7002 --timeout=60 -- ./start.sh"
