global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'opal_server'
    static_configs:
      - targets: ['opal_server:7002']
    metrics_path: '/metrics'

  - job_name: 'opal_client'
    static_configs:
      - targets: ['opal_client:7000']
    metrics_path: '/metrics'
