// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  opalSidebar: [
    {
      type: "doc",
      id: "welcome",
      label: "Welcome",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "getting-started/intro",
          label: "Introduction",
        },
        {
          type: "category",
          label: "Quickstart",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "category",
              label: "OPAL Playground",
              collapsible: true,
              collapsed: false,
              items: [
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/overview",
                  label: "Overview",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/run-server-and-client",
                  label: "Run Server and Client",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/send-queries-to-opa",
                  label: "Send Queries to OPA",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/updating-the-policy",
                  label: "Updating the Policy",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/publishing-data-update",
                  label: "Publishing Data Updates",
                },
              ],
            },
            {
              type: "category",
              collapsible: true,
              label: "Docker Compose Config",
              items: [
                {
                  type: "doc",
                  id: "getting-started/quickstart/docker-compose-config/overview",
                  label: "Overview",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/docker-compose-config/postgres-database",
                  label: "Broadcast Channel",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/docker-compose-config/opal-server",
                  label: "OPAL Client",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/docker-compose-config/opal-client",
                  label: "OPAL Server",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          collapsible: true,
          label: "Running OPAL",
          items: [
            {
              type: "category",
              collapsible: true,
              label: "as Python Packages",
              items: [
                {
                  type: "doc",
                  id: "getting-started/running-opal/as-python-package/overview",
                  label: "Overview",
                },
                {
                  type: "doc",
                  id: "getting-started/running-opal/as-python-package/opal-server-setup",
                  label: "OPAL Server Setup",
                },
                {
                  type: "doc",
                  id: "getting-started/running-opal/as-python-package/opal-client-setup",
                  label: "OPAL Client Setup",
                },
                {
                  type: "doc",
                  id: "getting-started/running-opal/as-python-package/secure-mode-setup",
                  label: "Secure Mode Setup",
                },
              ],
            },
            {
              type: "category",
              collapsible: true,
              label: "as Docker Images",
              items: [
                {
                  type: "doc",
                  id: "getting-started/running-opal/as-docker-image/overview",
                  label: "Overview",
                },
                {
                  type: "doc",
                  id: "getting-started/running-opal/as-docker-image/run-opal",
                  label: "Full Guide",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "OPAL Basics",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "overview",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials",
        },
      ],
    },
    {
      type: "doc",
      id: "FAQ",
      label: "FAQ",
    },
  ],
};

module.exports = sidebars;
