// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  opalSidebar: [
    {
      type: "doc",
      id: "welcome",
      label: "Welcome",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "getting-started/intro",
          label: "Introduction",
        },
        {
          type: "category",
          label: "Quickstart",
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "getting-started/get_started_with_opal_docker_compose_tutorial",
              label: "start",
            },
            // {
            //   type: "doc",
            //   id: "getting-started/get_started_with_opal_using_docker",
            //   label: "official docker images",
            // },
            {
              type: "category",
              label: "OPAL Playground",
              collapsible: true,
              collapsed: false,
              items: [
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/overview",
                  label: "Overview",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/run-server-and-client",
                  label: "Run Server and Client",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/send-queries-to-opa",
                  label: "Send Queries to OPA",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/updating-the-policy",
                  label: "Updating the Policy",
                },
                {
                  type: "doc",
                  id: "getting-started/quickstart/opal-playground/publishing-data-update",
                  label: "Publishing Data Update",
                },
              ],
            },
            {
              type: "doc",
              id: "getting-started/quickstart/understanding-config",
              label: "Understanding Config",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "OPAL Basics",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "overview",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials",
        },
      ],
    },
    {
      type: "doc",
      id: "FAQ",
      label: "FAQ",
    },
  ],
};

module.exports = sidebars;
