name: pre-commit

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: install pre-commit
      run: python -m pip install 'pre-commit<4'
    - name: show environment
      run: python -m pip freeze --local
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
