name: Sync master to OPAL Plus

on:
  push:
    branches:
      - sync-test
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git configuration
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout permitio/opal repository
        uses: actions/checkout@v4
        with:
          repository: permitio/opal
          ref: sync-test
          path: opal
          fetch-depth: 0

      - name: Checkout permitio/opal-plus repository
        uses: actions/checkout@v4
        with:
          repository: permitio/opal-plus
          ref: public-master
          path: opal-plus
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Rebase opal-plus:public-master onto opal:master
        working-directory: opal-plus
        run: |
          git remote add opal ../opal
          git fetch opal
          git checkout public-master
          git rebase opal/sync-test

      - name: Push changes to opal-plus public-master branch
        working-directory: opal-plus
        run: |
          git push origin public-master

      - name: Create Pull Request for opal-plus
        working-directory: opal-plus
        run: |
          gh pr create --repo permitio/opal-plus --assignee "$GITHUB_ACTOR" --reviewer "$GITHUB_ACTOR" --base master --head public-master --title "Sync changes from public OPAL repository" --body "This PR synchronizes changes from the public OPAL repository to the private OPAL Plus repository."
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
