# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-cedar-test-1:
    runs-on: ubuntu-latest
    steps:
      # BUILD PHASE
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Show cedar-agent
        run: |
          ls -la ./cedar-agent

      - name: Build client cedar
        id: build_client
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: false
          target: client-cedar
          cache-from: type=registry,ref=permitio/opal-client-cedar:latest
          cache-to: type=inline
          load: true
          tags: |
            permitio/opal-client-cedar:test

  build-cedar-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Show cedar-agent
        run: |
          ls -la ./cedar-agent

      - name: Build & Push client cedar
        id: build_push_client_cedar
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          target: client-cedar
          cache-from: type=registry,ref=permitio/opal-client-cedar:latest
          cache-to: type=inline
          tags: |
            permitio/opal-client-cedar:latest
